language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - vuepress build docs

after_script:
  - cd docs/.vuepress/dist
  - git init
  - git config user.name "chengzhaojia"
  - git config user.email "380333756@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/czjroy/vuepress.github.io
